### ISSUE TITLE
Should I use this?

### ISSUE THREAD

**Issue by nandorojo** [ext/semantic-release-lerna#39]
Hey there @ext!

Saw you mention this is a WIP so just wanted to see if you recommend using it.

I have an app (not an NPM module) in a monorepo. I use `lerna` just to help me maintain versions. I want to use semantic release now to track my changes and stuff.

Basically, I'd like to make commits, have semantic-release tell me which version to use, and then have those apply to the packages in my monorepo.

I'm new to semantic-release, so I'm not totally sure how to achieve this. I'm also sort of new to lerna, but I already use it.

Would love your thoughts if you don't mind sharing. Thank you!

**Comment by ext** [comment]
Hi, thank you for your interest. It sure is work in progress but I do use it in a few production environments. The two major points is that there are still bugs being ironed out and it still lacks some features which would probably be expected of the plugin. But other than that it works pretty decent.

Now as for your use-case I am not sure if this is a good fit or not as I do not fully understand your monorepo structure and how the application is related to the monorepo.

From my understanding you have a layout similar to:

```
root
└── packages
  ├── library-a
  ├── library-b
  └── app
```

where `library-a` and `library-b` are both used by `app` but not otherwise published as NPM packages? E.g. the application bundles the library using `webpack`, `parcel`, `rollup` or similar?

Since you use `lerna` I assume you have a `package.json` in each package? Does the version matter for anything else than the application?

Given the assumption that the libraries are bundled into the application and their version doesn't really matter but for simplicity should just follow the same version I see two options:

* you can set `private` to `true` in `package.json` for everything. This will change the behavior of `lerna` as well since some commands ignore private packages entirely. As for `semantic-release-lerna` it should work out-of-the-box, i.e. update the version number in all packages but not publish any of them.
* add a feature request to `semantic-release-lerna` to implement the option `npmPublish` (similar to [@semantic-release/npm](https://github.com/semantic-release/npm)), i.e. disable the publish step.

As an alternative you could skip `lerna` for managing versions only use it for managing the monorepo. Set version to `0.0.0` for everything but the root `package.json` and let the application use the version from root.

Hope that helps, let me know if I misunderstood any of your requirements or have more questions!

**Comment by ext** [comment]
Closing this for now, if you have further questions or issues feel free to reopen.
